removendo libs desnecessárias

diff --git a/.github/workflows/sync_and_update.yml b/.github/workflows/sync_and_update.yml
--- a/.github/workflows/sync_and_update.yml
+++ b/.github/workflows/sync_and_update.yml
@@ -16,13 +16,12 @@ jobs:
         repository: AndyTargino/wwebjs-electron
         fetch-depth: 0
 
-    - name: Obter a última versão do pull request
+    - name: Obter a última versão do whatsapp-web.js
       id: latest_version
       run: |
-        PULL_REQUEST_URL="https://api.github.com/repos/pedroslopez/whatsapp-web.js/pulls/2816"
-        BASE_REF=$(curl --silent $PULL_REQUEST_URL | jq -r '.base.ref')
-        echo "Base ref do PR: $BASE_REF"
-        echo "::set-output name=version::$BASE_REF"
+        LATEST_TAG=$(curl --silent "https://api.github.com/repos/pedroslopez/whatsapp-web.js/tags" | jq -r '[.[] | .name | select(test("^v[0-9]+\\.[0-9]+\\.[0-9]+$"))][0]')
+        echo "Última versão do whatsapp-web.js: $LATEST_TAG"
+        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
       env:
         GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
 
@@ -31,15 +30,25 @@ jobs:
       run: |
         MY_LATEST_VERSION=$(curl --silent "https://api.github.com/repos/AndyTargino/wwebjs-electron/releases/latest" | jq -r .tag_name)
         LATEST_LIB_VERSION=${{ steps.latest_version.outputs.version }}
-        MOST_RECENT=$(printf "%s\n%s\n" "$MY_LATEST_VERSION" "$LATEST_LIB_VERSION" | sort -V | tail -1)
-        echo "Versão obtida: $MOST_RECENT"
-        echo "Minha versão: $MY_LATEST_VERSION"
-        if [[ "$MOST_RECENT" == "$MY_LATEST_VERSION" ]]; then
-        echo "AS VERSÕES SÃO IGUAIS"
-          echo "::set-output name=should_continue::false"
+
+        if [ -z "$LATEST_LIB_VERSION" ]; then
+          echo "Não foi possível obter a última versão estável da biblioteca. Abortando."
+          echo "should_continue=false" >> $GITHUB_OUTPUT
+          exit 0
+        fi
+
+        CLEAN_LATEST_LIB_VERSION=$(echo "$LATEST_LIB_VERSION" | sed -e 's/^v//' -e 's/^\.//')
+        CLEAN_MY_LATEST_VERSION=$(echo "$MY_LATEST_VERSION" | sed -e 's/^v//' -e 's/^\.//')
+
+        echo "Versão da lib (limpa): $CLEAN_LATEST_LIB_VERSION"
+        echo "Minha versão (limpa): $CLEAN_MY_LATEST_VERSION"
+
+        if [ "$(printf '%s\n' "$CLEAN_LATEST_LIB_VERSION" "$CLEAN_MY_LATEST_VERSION" | sort -V | head -n1)" = "$CLEAN_MY_LATEST_VERSION" ] && [ "$CLEAN_LATEST_LIB_VERSION" != "$CLEAN_MY_LATEST_VERSION" ]; then
+          echo "Nova versão do whatsapp-web.js encontrada: $LATEST_LIB_VERSION (a sua é $MY_LATEST_VERSION)"
+          echo "should_continue=true" >> $GITHUB_OUTPUT
         else
-          echo "As versões são diferentes"
-          echo "::set-output name=should_continue::true"
+          echo "Sua versão $MY_LATEST_VERSION está atualizada."
+          echo "should_continue=false" >> $GITHUB_OUTPUT
         fi
       env:
         GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
@@ -66,63 +75,44 @@ jobs:
         PACKAGE_VERSION=$(jq -r .version whatsapp-web.js/package.json)
         jq '.version = $newVersion' --arg newVersion "$PACKAGE_VERSION" package.json > temp.json && mv temp.json package.json
         FILE_PATH="src/Client.js"
-        sed -i "s|const puppeteer = require('puppeteer');|const pie = require('puppeteer-in-electron');|" $FILE_PATH
-        sed -i "s|constructor(options = {}) {|constructor(puppeteerBrowser, browserWindow, options = {}) {|" $FILE_PATH
-        sed -i "s|this.pupBrowser = null;|this.pupBrowser = puppeteerBrowser;\nthis.browserWindow = browserWindow;|" $FILE_PATH
-        sed -i "/let \[browser, page\] = \[null, null\];/,/this.pupPage = page;/c const page = await pie.getPage(this.pupBrowser, this.browserWindow);\npage.setUserAgent(this.options.userAgent);\n\nawait page.setUserAgent(this.options.userAgent);\nif (this.options.bypassCSP) await page.setBypassCSP(true);\n\nthis.pupPage = page;" $FILE_PATH
-        sed -i "/this.pupBrowser = browser;/d" $FILE_PATH
-        
-        # Exibindo o conteúdo do arquivo modificado
-        cat $FILE_PATH
-    
-    - name: Verificar se há commits novos
-      id: check_commits
+        sed -i 's#if (puppeteerOpts && (puppeteerOpts.browserWSEndpoint || puppeteerOpts.browserURL))#if (this.options.page) { page = this.options.page; browser = page.browser(); } else if (puppeteerOpts && (puppeteerOpts.browserWSEndpoint || puppeteerOpts.browserURL))#' $FILE_PATH
+
+    - name: Verificar se há alterações nos arquivos
+      id: check_diff
       if: steps.check_version.outputs.should_continue == 'true'
       run: |
-        NEW_COMMITS=$(git log main..temp-sync-branch --oneline)
-        if [ -z "$NEW_COMMITS" ]; then
-          echo "Não há commits novos"
-          echo "::set-output name=has_changes::true"
-        else
-          echo "Há commits novos"
-          echo "::set-output name=has_changes::true"
-        fi
+        git diff --quiet && echo "has_changes=false" >> $GITHUB_OUTPUT || echo "has_changes=true" >> $GITHUB_OUTPUT
 
     - name: Commit e Push
-      if: steps.check_version.outputs.should_continue == 'true'
+      if: steps.check_version.outputs.should_continue == 'true' && steps.check_diff.outputs.has_changes == 'true'
       run: |
         git config user.email "andytargino@outlook.com"
         git config user.name "AndyTargino"
         git add .
         git commit -m "Synchronized with upstream and applied custom changes" || echo "No changes to commit"
         git remote set-url origin https://${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com/AndyTargino/wwebjs-electron.git
-        git pull origin main --rebase  # Update your branch with the latest changes from main
-        git push --set-upstream origin temp-sync-branch
+        git pull origin main --rebase
+        git push --force --set-upstream origin temp-sync-branch
       env:
           GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
 
-    - name: Verificar se deve continuar com a mesclagem
-      run: |
-        echo "O codigo deve continuar?"
-        echo "should_continue: ${{ steps.check_version.outputs.should_continue }}"
-        echo "has_changes: ${{ steps.check_commits.outputs.has_changes }}"
-
     - name: Criar e mesclar Pull Request
-      if: steps.check_version.outputs.should_continue == 'true' && steps.check_commits.outputs.has_changes == 'true'
+      if: steps.check_version.outputs.should_continue == 'true' && steps.check_diff.outputs.has_changes == 'true'
       run: |
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git config --global user.name "GitHub Actions"
         git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/AndyTargino/wwebjs-electron.git
-        PR_ID=$(gh pr create --base main --head temp-sync-branch --title "Synchronized with upstream and applied custom changes" --body "This PR includes the latest changes from the upstream and our custom changes." | grep -oP 'github.com/.+/pull/\K\d+')
-        gh pr merge $PR_ID --auto --merge
+        PR_ID=$(gh pr create --base main --head temp-sync-branch --title "Sync with whatsapp-web.js ${{ steps.latest_version.outputs.version }}" --body "This PR includes the latest changes from the upstream and our custom changes." | grep -oP 'github.com/.+/pull/\K\d+')
+        gh pr merge $PR_ID --merge
       env:
           GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
 
     - name: Criar release
-      if: steps.check_version.outputs.should_continue == 'true' && steps.check_commits.outputs.has_changes == 'true'
+      if: steps.check_version.outputs.should_continue == 'true' && steps.check_diff.outputs.has_changes == 'true'
       run: |
-        VERSION=$(jq -r .version package.json)
-        gh release create $VERSION
+        VERSION_TAG=${{ steps.latest_version.outputs.version }}
+        echo "Criando release: $VERSION_TAG"
+        gh release create "$VERSION_TAG" --title "$VERSION_TAG" --notes "Synchronized with whatsapp-web.js version $VERSION_TAG"
       env:
           GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
 
